---
- name: Create kubeadm config file
  ansible.builtin.template:
    dest: /etc/kubeadm.yml
    src: "{{ kubeadm_template }}"
    mode: "0600"

- name: Kubeadm pull images
  ansible.builtin.shell: kubeadm config images pull --config /etc/kubeadm.yml --cri-socket {{ cri_socket }}

- name: Delete kubeadm config
  ansible.builtin.file:
    path: /etc/kubeadm.yml
    state: absent
  when: ansible_os_family != "Flatcar"
